"""empty message

Revision ID: 46b7ebdfae12
Revises: 
Create Date: 2024-02-08 16:52:48.056930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b7ebdfae12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquiry_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('arrival', sa.String(length=100), nullable=True),
    sa.Column('departure', sa.String(length=100), nullable=True),
    sa.Column('arrival_time', sa.String(length=100), nullable=True),
    sa.Column('departure_time', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('budget', sa.String(length=100), nullable=False),
    sa.Column('requests', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inquiry_form')
    # ### end Alembic commands ###
