"""empty message

Revision ID: b6eb06869484
Revises: eb1c5dfdcb0c
Create Date: 2024-02-09 13:01:24.685984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6eb06869484'
down_revision = 'eb1c5dfdcb0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry_form', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
