"""empty message

Revision ID: cc5984bfc6aa
Revises: 46b7ebdfae12
Create Date: 2024-02-09 03:30:31.131426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc5984bfc6aa'
down_revision = '46b7ebdfae12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_column('arrival_time')
        batch_op.drop_column('departure_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure_time', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('arrival_time', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
