"""empty message

Revision ID: eb1c5dfdcb0c
Revises: cc5984bfc6aa
Create Date: 2024-02-09 12:16:13.016240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1c5dfdcb0c'
down_revision = 'cc5984bfc6aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arrival_time', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('departure_time', sa.String(length=100), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('departure_time')
        batch_op.drop_column('arrival_time')

    # ### end Alembic commands ###
